import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'te', name: 'Telugu', label: 'తెలుగు' },
  { code: 'en', name: 'English', label: 'English' },
  { code: 'hi', name: 'Hindi', label: 'हिन्दी' },
  { code: 'ta', name: 'Tamil', label: 'தமிழ்' },
  { code: 'kn', name: 'Kannada', label: 'ಕನ್ನಡ' },
  { code: 'mr', name: 'Marathi', label: 'मराठी' },
];



export const translations = {
  en: {
    // Brand & Nav
    appName: 'KisaanSathi',
    tagline: 'Smart Crop Companion',
    navHome: 'Home',
    navServices: 'Services',
    navAbout: 'About',
    navContact: 'Contact',
    navReport: 'Report Problem',
    navMyFarm: 'My Farm',
    navOfficerLogin: 'Officer Login',
    apiConnected: 'API Connected',
    apiConnecting: 'Connecting...',
    apiOffline: 'API Offline',

    // Landing Page Hero
    heroBadge: 'Standing with farmers, at every step',
    heroBrand: 'KisaanSathi',
    heroTitle: 'Smart Companion for Your Crop',
    heroDescription: 'Powered by multimodal AI to understand crop symptoms via voice, video & photos, delivering rapid, verified remedies from agricultural officers.',
    heroCta: 'Got a Problem? Report Now →',
    heroAudioHint: 'Easy registration via Voice, Video & Photo',
    
    // How It Works / User Flow
    howItWorksTitle: 'Our Workflow',
    howItWorksSubtitle: 'How KisaanSathi turns crop questions into verified solutions in 4 simple steps',
    step1Num: '1',
    step1Title: 'Report Problem',
    step1Text: 'Describe your issue easily using voice recording, video scan, photos, or text in your native language.',
    step2Num: '2',
    step2Title: 'AI Analysis',
    step2Text: 'Our agricultural AI analyzes plant symptoms, pest signs, and visual damage instantly.',
    step3Num: '3',
    step3Title: 'Expert & Officer Advice',
    step3Text: 'Agricultural Extension Officers (AEO) verify diagnosis and prescribe precise, safe remedies.',
    step4Num: '4',
    step4Title: 'Better & Healthier Crop',
    step4Text: 'Apply the exact recommended treatment to protect yield and maximize harvest profit.',

    // AI Feature Deep Dive
    aiFeatureBadge: 'Multimodal AI Intelligence',
    aiFeatureTitle: 'A New Era for Agriculture Powered by AI',
    aiFeatureDesc: 'Never struggle to identify complex pests or leaf diseases. With KisaanSathi, you can simply speak in your local language or record a short video of the affected crop.',
    aiFeature1: 'Accurate analysis powered by advanced multimodal AI vision & speech models',
    aiFeature2: 'Full support for Voice, Video scans, High-res Photos, and Text in regional dialects',
    aiFeature3: 'Instant preliminary guidance backed by official Agricultural Officer validation',
    aiFeature4: 'Specially trained and optimized for Indian farming conditions and crops',

    // Comparison Section
    comparisonTitle: 'Why We Are Better Compared to Traditional Methods',
    comparisonSubtitle: 'Experience the modern agricultural advantage over slow, costly conventional practices',
    traditionalTitle: 'Traditional Method',
    traditionalItem1: 'Takes days to visit or meet agricultural officers',
    traditionalItem2: 'Accurate diagnostic data and remedies are hard to find',
    traditionalItem3: 'High travel and consultation expenses',
    traditionalItem4: 'Delayed advisory often leads to severe crop damage',
    kisaanTitle: 'KisaanSathi',
    kisaanItem1: 'Instant 24/7 assistance anytime, anywhere from your farm',
    kisaanItem2: 'Cutting-edge AI + verified Agriculture Extension Officer advice',
    kisaanItem3: 'Zero cost & ultra easy to use in your native mother tongue',
    kisaanItem4: 'Rapid, scientifically proven solutions in minutes',

    // Stats Bar
    stat1Value: '10K+',
    stat1Label: 'Farmers Trust Us',
    stat2Value: '25K+',
    stat2Label: 'Problems Resolved',
    stat3Value: '50+',
    stat3Label: 'Crops Covered',
    stat4Value: '99%',
    stat4Label: 'Satisfaction Rating',

    // Bottom CTA Banner
    ctaBannerTitle: 'No more waiting for crop solutions!',
    ctaBannerSubtitle: 'Take a step forward with KisaanSathi and secure your harvest today.',
    ctaBannerBtn: 'Report Issue Now →',

    // Farmer Page / Form
    formTitle: 'Got a doubt about your crop?',
    formSubtitle: "Tell us what's happening by voice or text. No login or password required.",
    labelName: 'Your Name',
    placeholderName: 'e.g. Ramesh Reddy',
    labelPhone: 'Mobile Number',
    placeholderPhone: 'e.g. 9876543210 or +91 9876543210',
    phoneHint: 'Used only for officer contact and reference lookup. No OTP needed.',
    labelCrop: 'Crop Name (Optional)',
    placeholderCustomCrop: 'Specify crop name',
    labelDescription: 'Describe the problem (or use voice below)',
    placeholderDescription: 'Describe what you see: leaves turning yellow, holes in leaves, stem borer, rotting, etc.',
    labelVoice: 'Speak Your Problem (Voice Recording)',
    btnStartRecording: 'Record Voice Problem',
    btnStopRecording: 'Done Recording',
    btnRecordAgain: 'Record Again',
    btnClearVoice: 'Remove Voice',
    voiceAttached: 'Voice Note Recorded',
    voiceRecordingActive: 'Recording... Speak now',
    voiceHint: 'Speak in your own language (Telugu, English, Tamil, Hindi). AI will transcribe and analyze it.',
    micPermissionDenied: 'Microphone permission was denied. Please allow microphone access in your browser settings.',
    micError: 'Could not access microphone.',
    voiceUnsupported: 'Voice recording is not supported in this browser.',
    labelPhoto: 'Add a Photo or Video Evidence (Optional)',
    btnTakePhoto: 'Take Photo / Video Scan',
    btnRemovePhoto: 'Remove Photo',
    photoHint: 'Clear photos of affected leaves or pests help officers diagnose quickly.',
    labelLocation: 'Field Location',
    gpsDetecting: 'Detecting GPS location...',
    gpsDetected: 'GPS Location Detected',
    gpsDenied: 'GPS not enabled',
    gpsDeniedHint: 'Your report will still be submitted successfully without GPS.',
    btnRetryGps: 'Retry GPS',
    btnSubmit: 'Submit Problem',
    btnSubmitting: 'Submitting Problem & Processing AI Analysis...',
    errorTitle: 'Submission Error',
    valNameRequired: 'Please enter your name.',
    valPhoneRequired: 'Please enter your 10-digit mobile number.',
    valDescRequired: 'Please describe the problem or record a voice note.',
    valPhotoSize: 'Photo file size must be less than 10MB.',

    // Confirmation Screen
    successTitle: 'Problem Reported Successfully',
    successSubtitle: 'Your agricultural issue has been recorded',
    refIdLabel: 'Reference ID',
    confirmMessage: 'Your agricultural problem has been recorded in our system.',
    confirmNextStep: 'Our system will process the report and route it to the appropriate agricultural officer.',
    summaryTitle: 'Submission Summary',
    summaryFarmerName: 'Farmer Name',
    summaryMobile: 'Mobile Number',
    summaryCrop: 'Crop',
    summaryGps: 'GPS Location',
    summaryPhoto: 'Photo Attachment',
    summaryVoice: 'Voice Note',
    aiInsightsTitle: 'AI Multimodal & Agricultural Speech Diagnosis',
    aiTranscriptLabel: 'Speech Transcript',
    aiSummaryLabel: 'Agricultural Summary',
    aiSymptomsLabel: 'Identified Symptoms',
    aiConditionsLabel: 'Preliminary Possibilities',
    aiAeoReviewLabel: 'Human AEO Review Assigned',
    valAttached: 'Attached',
    valNone: 'None',
    valNotProvided: 'Not Provided',
    btnReportAnother: 'Report Another Problem',
    btnBackHome: 'Back to Home',

    // Officer Page
    officerTitle: 'Agricultural Officer Portal',
    officerSubtitle: 'Extension Officers (AEO) & Agriculture Department Portal',
    officerNoticeTitle: 'Officer Authentication',
    officerNoticeText: 'Officer login, field assignment, and incident management dashboard.',
    officerNoticeSubtext: 'Farmers can continue to submit crop incidents directly without logging in.',
    btnReturnFarmer: '← Return to Farmer Incident Reporting',

    // Footer
    footerTitle: 'AI Smart Agriculture Incident & Advisory Platform',
    footerSubtext: 'Empowering farmers with instant AI diagnosis & direct connection to Agricultural Extension Officers.',

    // Crops List
    crops: [
      { value: 'Paddy', label: 'Paddy (Rice)' },
      { value: 'Chilli', label: 'Chilli' },
      { value: 'Cotton', label: 'Cotton' },
      { value: 'Maize', label: 'Maize (Corn)' },
      { value: 'Red Gram', label: 'Red Gram (Pigeon Pea)' },
      { value: 'Tomato', label: 'Tomato' },
      { value: 'Groundnut', label: 'Groundnut' },
      { value: 'Sugarcane', label: 'Sugarcane' },
      { value: 'Other', label: 'Other Crop' },
    ],

    // AI Assistant Conversational Flow
    aiAssistant: {
      screen1Title: 'Start a Complaint',
      screen1Subtitle: 'Talk directly with your agricultural AI assistant in one simple voice message. We will understand your problem and alert your local Agricultural Extension Officer (AEO).',
      btnStartComplaint: 'Start Complaint →',
      greeting: 'Tell me about your farming problem.',
      listeningNotice: 'Listening... Describe your problem naturally in one voice message',
      processingVoice: 'Understanding your voice complaint...',
      btnRecordVoice: '🎙️ Record Complaint',
      btnStopRecording: '⏹️ Done Speaking',
      btnRecordAgain: '🔄 Record Again',
      summaryHeading: 'Your Complaint Details',
      summaryCheckPrompt: 'Does this correctly describe your problem?',
      btnConfirmSummary: '✓ Yes, Continue',
      btnEditSummary: '✏️ Edit / Record Again',
      labelCrop: 'Crop',
      labelProblem: 'Problem',
      labelDuration: 'Duration',
      labelProgress: 'Progress',
      defaultPhotoPrompt: 'Please take clear photos of the affected parts so I can understand the problem better.',
      btnTakePhoto: '📷 Take Photo',
      btnChooseGallery: '🖼️ Choose Photo',
      photoCountNotice: '1 to 4 photos (at least 1 good photo is sufficient)',
      btnSubmitComplaint: '🚀 Submit to Agricultural Officer',
      submittingText: 'Submitting complaint & inspecting photos...',
      photoRetryTitle: 'Clearer Photo Required',
      photoRetryPrompt: 'The photo is not clear enough to understand the problem. Please send another photo showing the affected part clearly.',
      photoWrongCropPrompt: 'The uploaded photo does not appear to match your reported crop problem. Your voice complaint is safe. Please upload a clear photo of the affected plant.',
      photoHealthyCropPrompt: 'The uploaded photo shows healthy plants without visible disease or pest symptoms. Please upload a photo of the affected plant part.',
      btnRetryPhoto: '📷 Try Another Photo',
      voicePreservedNote: '✓ Your voice complaint is safe and does not need to be re-recorded.',
      similarIssuesTitle: 'Similar Issues Check',
      similarIssuesIntro: 'While routing your complaint to your local Agricultural Officer (AEO), check if any of these previous cases match your crop problem:',
      btnLooksLikeMyProblem: 'Looks Like My Problem',
      btnConfirmIssue: '✓ Confirm Issue',
      btnNoneOfTheseMatch: 'None of These Match →',
      noSimilarIssuesFound: 'No similar previous cases found nearby. Your complaint is submitted directly to your AEO.',
      similarIssuesCheckFailed: 'Your complaint was received safely. Proceeding to confirmation...',
      aeoVerifiedBadge: 'Verified by Agricultural Officer',
      previousOutcomeLabel: 'Previous Case Outcome',
      btnContinuing: 'Continuing...',
      successHeading: 'Complaint Submitted Successfully!',
      successSubheading: 'Your local Agricultural Extension Officer (AEO) has been notified.',
      trackingRefLabel: 'Tracking Reference ID',
      btnReportAnother: 'Report Another Problem',
      btnViewMyIssues: '📋 My Issues',
    },
  },

  te: {
    // Brand & Nav
    appName: 'కిసాన్‌సాథి',
    tagline: 'రైతు సేవలు',
    navHome: 'హోమ్',
    navServices: 'సేవలు',
    navAbout: 'గురించి',
    navContact: 'సంప్రదించండి',
    navReport: 'సమస్య నమోదు',
    navMyFarm: 'నా పొలం (3 Pillars)',
    navOfficerLogin: 'అధికారుల లాగిన్',
    apiConnected: 'సర్వర్ అనుసంధానించబడింది',
    apiConnecting: 'అనుసంధానిస్తోంది...',
    apiOffline: 'సర్వర్ ఆఫ్‌లైన్',

    // Landing Page Hero
    heroBadge: 'రైతుకి తోడుగా, ప్రతి అడుగులో',
    heroBrand: 'KisaanSathi',
    heroTitle: 'మీ పంటకు తెలివైన తోడు',
    heroDescription: 'AI ఆధారిత సాంకేతికతతో మీ సమస్యను అర్థం చేసుకుని, వేగంగా పరిష్కారాలను అందించే మీ నమ్మకమైన వ్యవసాయ సహకారి.',
    heroCta: 'సమస్య ఉందా? నివేదించండి →',
    heroAudioHint: 'ఆడియో ద్వారా సులభంగా నమోదు చేయండి',

    // How It Works / User Flow
    howItWorksTitle: 'మా పని విధానం',
    howItWorksSubtitle: 'KisaanSathi తో 4 సులభమైన దశల్లో మీ పంట సమస్యకు పరిష్కారం పొందండి',
    step1Num: '1',
    step1Title: 'సమస్య నమోదు',
    step1Text: 'ఆడియో / వీడియో / ఫోటో / టెక్స్ట్ ద్వారా మీ పంట సమస్యను సులభంగా నమోదు చేయండి.',
    step2Num: '2',
    step2Title: 'AI విశ్లేషణ',
    step2Text: 'మా AI మీ సమస్యను అర్థం చేసుకుని, తెగుళ్ల లక్షణాలను క్షణాల్లో విశ్లేషిస్తుంది.',
    step3Num: '3',
    step3Title: 'నిపుణుల సలహా',
    step3Text: 'వ్యవసాయ నిపుణులు & AEO అధికారుల నుండి శాస్త్రీయమైన, సరైన పరిష్కారాలు అందుతాయి.',
    step4Num: '4',
    step4Title: 'మెరుగైన పంట',
    step4Text: 'సరైన సలహాలు, సమర్థవంతమైన చర్యలతో ఆరోగ్యకరమైన, అధిక దిగుబడిని పొందండి.',

    // AI Feature Deep Dive
    aiFeatureBadge: 'AI సాంకేతికత',
    aiFeatureTitle: 'AI శక్తీతో వ్యవసాయానికి కొత్త దారి',
    aiFeatureDesc: 'పంట తెగులు లేదా సమస్య ఏదైనా, రాయాల్సిన పనిలేదు. మీ ప్రాంతీయ భాషలో మాట్లాడండి లేదా వీడియో / ఫోటో తీసి వెంటనే పరిష్కారం కనుగొనండి.',
    aiFeature1: 'అత్యాధునిక AI మోడల్స్‌తో అత్యంత ఖచ్చితమైన విశ్లేషణ',
    aiFeature2: 'ఫోటోలు, ఆడియో, వీడియో, టెక్స్ట్ అన్నింటికీ పూర్తి సపోర్ట్',
    aiFeature3: 'వేగవంతమైన మరియు అధికారికంగా నమ్మదగిన సలహాలు',
    aiFeature4: 'ప్రత్యేకంగా భారతీయ వ్యవసాయం, నేల పరిస్థితులకు రూపొందించినది',

    // Comparison Section
    comparisonTitle: 'సంప్రదాయ విధానాలతో పోలిస్తే మనం ఎందుకు మెరుగ్గా?',
    comparisonSubtitle: 'పాత పద్ధతులతో ఆలస్యం, ఖర్చు కాకుండా KisaanSathi తో వేగవంతమైన ప్రయోజనాలు',
    traditionalTitle: 'సంప్రదాయ విధానం',
    traditionalItem1: 'నిపుణులను కలిసేందుకు చాలా రోజుల సమయం పడుతుంది',
    traditionalItem2: 'ఖచ్చితమైన మరియు విశ్వసనీయ సమాచారం లభ్యం కాదు',
    traditionalItem3: 'ప్రయాణ ఖర్చులు, సమయం వృధా ఎక్కువ',
    traditionalItem4: 'సలహాలు ఆలస్యంగా లభించి పంట నష్టం పెరుగుతుంది',
    kisaanTitle: 'KisaanSathi',
    kisaanItem1: 'ఎప్పుడైనా, ఎక్కడి నుంచైనా 24/7 తక్షణ సహాయం',
    kisaanItem2: 'AI & వ్యవసాయ విస్తరణ అధికారుల (AEO) అత్యుత్తమ సలహాలు',
    kisaanItem3: 'వాయిస్ లేదా యాప్‌లో మీ సొంత భాషలో సులభంగా ఉపయోగించండి',
    kisaanItem4: 'వేగవంతమైన, శాస్త్రీయ పరిష్కారాలతో తక్షణ రక్షణ',

    // Stats Bar
    stat1Value: '10K+',
    stat1Label: 'రైతుల నమ్మకం',
    stat2Value: '25K+',
    stat2Label: 'సమస్యలు పరిష్కరించబడినవి',
    stat3Value: '50+',
    stat3Label: 'పంటలు కవర్ చేయబడినవి',
    stat4Value: '99%',
    stat4Label: 'సంతృప్తి రేటింగ్',

    // Bottom CTA Banner
    ctaBannerTitle: 'మీ పంట సమస్యకు ఇక వెయిట్ చేయాల్సిన అవసరం లేదు!',
    ctaBannerSubtitle: 'KisaanSathi తో కలిసి ముందడుగు వేయండి, మీ పంటను కాపాడుకోండి.',
    ctaBannerBtn: 'ఇప్పుడే నమోదు చేయండి →',

    // Farmer Page / Form
    formTitle: 'మీ పంట సమస్య ఏమిటి?',
    formSubtitle: 'లాగిన్ లేదా పాస్‌వర్డ్ అవసరం లేదు. మాట్లాడి లేదా వివరాలు రాసి నమోదు చేయండి.',
    labelName: 'మీ పేరు',
    placeholderName: 'ఉదా. రమేష్ రెడ్డి',
    labelPhone: 'మొబైల్ నంబర్',
    placeholderPhone: 'ఉదా. 9876543210 లేదా +91 9876543210',
    phoneHint: 'అధికారులు మిమ్మల్ని సంప్రదించడానికి మాత్రమే. OTP అవసరం లేదు.',
    labelCrop: 'పంట పేరు (ఐచ్ఛికం)',
    placeholderCustomCrop: 'పంట పేరును రాయండి',
    labelDescription: 'సమస్య వివరాలు (లేదా కింద మాట్లాడండి)',
    placeholderDescription: 'మీరు చూస్తున్న లక్షణాలు: ఆకులు పసుపు రంగులోకి మారడం, ఆకులకు రంధ్రాలు, పురుగులు, కుళ్ళు తెగులు మొదలైనవి.',
    labelVoice: 'వాయిస్ ద్వారా చెప్పండి (వాయిస్ రికార్డింగ్)',
    btnStartRecording: 'సమస్యను మాట్లాడి చెప్పండి',
    btnStopRecording: 'రికార్డింగ్ పూర్తయింది',
    btnRecordAgain: 'మళ్లీ మాట్లాడండి',
    btnClearVoice: 'వాయిస్ తొలగించండి',
    voiceAttached: 'వాయిస్ రికార్డ్ చేయబడింది',
    voiceRecordingActive: 'రికార్డ్ అవుతోంది... స్పష్టంగా మాట్లాడండి',
    voiceHint: 'తెలుగులో స్పష్టంగా మాట్లాడండి. AI మీ మాటలను విశ్లేషిస్తుంది.',
    micPermissionDenied: 'మైక్రోఫోన్ అనుమతి నిరాకరించబడింది. బ్రౌజర్ సెట్టింగ్స్‌లో మైక్రోఫోన్‌ను అనుమతించండి.',
    micError: 'మైక్రోఫోన్ పని చేయలేదు.',
    voiceUnsupported: 'ఈ బ్రౌజర్‌లో వాయిస్ రికార్డింగ్ సదుపాయం లేదు.',
    labelPhoto: 'ఫోటో లేదా వీడియో జోడించండి (ఐచ్ఛికం)',
    btnTakePhoto: 'ఫోటో తీయండి లేదా గ్యాలరీ నుండి ఎంచుకోండి',
    btnRemovePhoto: 'ఫోటో తొలగించండి',
    photoHint: 'బాధిత ఆకులు లేదా పురుగుల స్పష్టమైన ఫోటో అధికారుల నిర్ధారణకు సహాయపడుతుంది.',
    labelLocation: 'పొలం ప్రదేశం (GPS)',
    gpsDetecting: 'జీపీఎస్ స్థానాన్ని గుర్తిస్తోంది...',
    gpsDetected: 'జీపీఎస్ లొకేషన్ గుర్తించబడింది',
    gpsDenied: 'జీపీఎస్ ఆన్ చేయలేదు',
    gpsDeniedHint: 'జీపీఎస్ లేకపోయినా మీ సమస్య విజయవంతంగా నమోదవుతుంది.',
    btnRetryGps: 'మళ్లీ ప్రయత్నించండి',
    btnSubmit: 'సమస్యను సమర్పించండి',
    btnSubmitting: 'సమర్పిస్తోంది & వాయిస్ విశ్లేషిస్తోంది...',
    errorTitle: 'లోపం సంభవించింది',
    valNameRequired: 'దయచేసి మీ పేరు నమోదు చేయండి.',
    valPhoneRequired: 'దయచేసి మీ 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి.',
    valDescRequired: 'దయచేసి సమస్య వివరాలు రాయండి లేదా వాయిస్ రికార్డ్ చేయండి.',
    valPhotoSize: 'ఫోటో సైజు 10MB కన్నా తక్కువ ఉండాలి.',

    // Confirmation Screen
    successTitle: 'సమస్య విజయవంతంగా నమోదైంది',
    successSubtitle: 'మీ వ్యవసాయ సమస్య మా వ్యవస్థలో రికార్డ్ చేయబడింది',
    refIdLabel: 'గుర్తింపు సంఖ్య (Reference ID)',
    confirmMessage: 'మీ పంట సమస్య వివరాలు నమోదు చేయబడ్డాయి.',
    confirmNextStep: 'మా సిస్టమ్ ఈ నివేదికను సంబంధిత వ్యవసాయ అధికారికి పంపుతుంది.',
    summaryTitle: 'సమర్పించిన వివరాలు',
    summaryFarmerName: 'రైతు పేరు',
    summaryMobile: 'మొబైల్ నంబర్',
    summaryCrop: 'పంట',
    summaryGps: 'జీపీఎస్ లొకేషన్',
    summaryPhoto: 'ఫోటో',
    summaryVoice: 'వాయిస్ రికార్డింగ్',
    aiInsightsTitle: 'AI మాటల & పంట సమస్య విశ్లేషణ',
    aiTranscriptLabel: 'మాట్లాడిన వివరాలు (ట్రాన్స్‌క్రిప్ట్)',
    aiSummaryLabel: 'వ్యవసాయ సమస్య సారాంశం',
    aiSymptomsLabel: 'గుర్తించిన తెగులు లక్షణాలు',
    aiConditionsLabel: 'సంభావ్య తెగుళ్లు/సమస్యలు',
    aiAeoReviewLabel: 'AEO అధికారి ప్రత్యక్ష పరిశీలన అవసరం',
    valAttached: 'జోడించబడింది',
    valNone: 'లేదు',
    valNotProvided: 'ఇవ్వలేదు',
    btnReportAnother: 'మరొక సమస్యను నమోదు చేయండి',
    btnBackHome: 'హోమ్ పేజీకి వెళ్లండి',

    // Officer Page
    officerTitle: 'వ్యవసాయ అధికారుల పోర్టల్',
    officerSubtitle: 'వ్యవసాయ విస్తరణ అధికారులు (AEO) & వ్యవసాయ శాఖ',
    officerNoticeTitle: 'అధికారుల లాగిన్',
    officerNoticeText: 'అధికారుల లాగిన్ మరియు ఫీల్డ్ నిర్వహణ డ్యాష్‌బోర్డ్.',
    officerNoticeSubtext: 'రైతులు లాగిన్ లేకుండా నేరుగా పంట సమస్యలను నివేదించవచ్చు.',
    btnReturnFarmer: '← రైతు సమస్య నమోదు పేజీకి వెళ్లండి',

    // Footer
    footerTitle: 'కిసాన్‌సాథి &mdash; AI ఆధారిత రైతు సమస్యల పరిష్కార వేదిక',
    footerSubtext: 'రైతుల సమస్యలను నేరుగా వ్యవసాయ అధికారులకు మరియు AI ద్వారా వేగంగా చేరవేసే వేదిక.',

    // Crops List
    crops: [
      { value: 'వరి', label: 'వరి (Paddy)' },
      { value: 'మిరప', label: 'మిరప (Chilli)' },
      { value: 'పత్తి', label: 'పత్తి (Cotton)' },
      { value: 'మొక్కజొన్న', label: 'మొక్కజొన్న (Maize)' },
      { value: 'కందులు', label: 'కందులు (Red Gram)' },
      { value: 'టమాటా', label: 'టమాటా (Tomato)' },
      { value: 'వేరుశనగ', label: 'వేరుశనగ (Groundnut)' },
      { value: 'చెరకు', label: 'చెరకు (Sugarcane)' },
      { value: 'ఇతర పంట', label: 'ఇతర పంట (Other)' },
    ],

    // AI Assistant Conversational Flow
    aiAssistant: {
      screen1Title: 'సమస్య నమోదును ప్రారంభించండి',
      screen1Subtitle: 'మా AI వ్యవసాయ సహాయకుడికి మీ పంట సమస్యను ఒక్క వాయిస్ మెసేజ్‌లో చెప్పండి. మేము మీ సమస్యను అర్థం చేసుకుని స్థానిక వ్యవసాయ అధికారి (AEO)కి పంపుతాము.',
      btnStartComplaint: 'సమస్యను ప్రారంభించండి →',
      greeting: 'మీ వ్యవసాయ సమస్య గురించి చెప్పండి.',
      listeningNotice: 'వినడం జరుగుతోంది... మీ సమస్యను సహజంగా మాట్లాడండి',
      processingVoice: 'మీ మాటలను విశ్లేషిస్తున్నాము...',
      btnRecordVoice: '🎙️ మీ సమస్యను మాట్లాడండి',
      btnStopRecording: '⏹️ మాట్లాడటం పూర్తయింది',
      btnRecordAgain: '🔄 మళ్లీ మాట్లాడండి',
      summaryHeading: 'మీ సమస్య వివరాలు',
      summaryCheckPrompt: 'ఇది మీ సమస్యను సరిగ్గా వివరిస్తోందా?',
      btnConfirmSummary: '✓ అవును, కొనసాగించండి',
      btnEditSummary: '✏️ సరిదిద్దండి / మళ్లీ మాట్లాడండి',
      labelCrop: 'పంట',
      labelProblem: 'సమస్య',
      labelDuration: 'వ్యవధి',
      labelProgress: 'పురోగతి',
      defaultPhotoPrompt: 'మీ మొక్క సమస్యను బాగా అర్థం చేసుకోవడానికి కొన్ని ఫోటోలు పంపండి.',
      btnTakePhoto: '📷 ఫోటో తీయండి',
      btnChooseGallery: '🖼️ గ్యాలరీ నుండి ఎంచుకోండి',
      photoCountNotice: '1 నుండి 4 ఫోటోలు (కనీసం 1 మంచి ఫోటో సరిపోతుంది)',
      btnSubmitComplaint: '🚀 వ్యవసాయ అధికారికి పంపండి',
      submittingText: 'సమస్య నమోదు అవుతోంది...',
      photoRetryTitle: 'మరొక ఫోటో అవసరం',
      photoRetryPrompt: 'సమస్యను అర్థం చేసుకోవడానికి ఫోటో స్పష్టంగా లేదు లేదా పంటకు సంబంధించినది కాదు. దయచేసి ప్రభావిత భాగాన్ని స్పష్టంగా చూపిస్తూ మరొక ఫోటో పంపండి.',
      photoWrongCropPrompt: 'మీరు పంపిన ఫోటో మీ సమస్యకు లేదా పంటకు సంబంధించినదిగా కనిపించడం లేదు. మీ వాయిస్ నమోదు భద్రంగా ఉంది. దయచేసి మీ పంట దెబ్బతిన్న భాగాన్ని స్పష్టంగా చూపిస్తూ మరొక ఫోటో పంపండి.',
      photoHealthyCropPrompt: 'అప్‌లోడ్ చేసిన ఫోటోలో ఎటువంటి తెగులు లేదా సమస్య కనిపించడం లేదు. మీ వాయిస్ నమోదు భద్రంగా ఉంది. దయచేసి సమస్య ఉన్న భాగాన్ని స్పష్టంగా చూపిస్తూ ఫోటో పంపండి.',
      btnRetryPhoto: '📷 మరొక ఫోటో పంపండి',
      voicePreservedNote: '✓ మీ వాయిస్ నమోదు భద్రంగా ఉంది, మళ్లీ మాట్లాడాల్సిన అవసరం లేదు.',
      similarIssuesTitle: 'సారూప్య సమస్యల పరిశీలన',
      similarIssuesIntro: 'మీ ఫిర్యాదు సంబంధిత వ్యవసాయ అధికారి (AEO) వద్దకు పంపబడుతోంది. ఇంతకు ముందు నమోదైన ఈ కేసులు మీ సమస్యతో సరిపోలుతున్నాయా పరిశీలించండి:',
      btnLooksLikeMyProblem: 'నా సమస్యలాగే ఉంది',
      btnConfirmIssue: '✓ సమస్యను నిర్ధారించండి',
      btnNoneOfTheseMatch: 'ఇవేవీ సరిపోలడం లేదు →',
      noSimilarIssuesFound: 'సమీపంలో సారూప్య మునుపటి కేసులు ఏవీ కనిపించలేదు. మీ ఫిర్యాదు నేరుగా వ్యవసాయ అధికారికి పంపబడింది.',
      similarIssuesCheckFailed: 'మీ ఫిర్యాదు సురక్షితంగా నమోదైంది. నిర్ధారణకు కొనసాగుతోంది...',
      aeoVerifiedBadge: 'వ్యవసాయ అధికారిచే ధృవీకరించబడింది',
      previousOutcomeLabel: 'గత కేసు పరిష్కారం',
      btnContinuing: 'కొనసాగుతోంది...',
      successHeading: 'మీ సమస్య విజయవంతంగా నమోదైంది!',
      successSubheading: 'మీ ప్రాంతీయ వ్యవసాయ విస్తరణ అధికారి (AEO)కి సమాచారం చేరింది.',
      trackingRefLabel: 'ట్రాకింగ్ రిఫరెన్స్ నంబర్',
      btnReportAnother: 'మరొక సమస్యను నమోదు చేయండి',
      btnViewMyIssues: '📋 నా సమస్యలు',
    },
  },

  hi: {
    // Brand & Nav
    appName: 'किसानसाथी',
    tagline: 'स्मार्ट फसल साथी',
    navHome: 'होम',
    navServices: 'सेवाएं',
    navAbout: 'हमारे बारे में',
    navContact: 'संपर्क करें',
    navReport: 'समस्या दर्ज करें',
    navMyFarm: 'मेरा खेत',
    navOfficerLogin: 'अधिकारी लॉगिन',
    apiConnected: 'सर्वर कनेक्टेड',
    apiConnecting: 'कनेक्ट हो रहा है...',
    apiOffline: 'सर्वर ऑफलाइन',

    // Landing Page Hero
    heroBadge: 'किसान के साथ, हर कदम पर',
    heroBrand: 'KisaanSathi',
    heroTitle: 'आपकी फसल का स्मार्ट साथी',
    heroDescription: 'AI आधारित तकनीक से फसल की समस्याओं को समझकर तुरंत समाधान और कृषि अधिकारियों से विश्वसनीय सलाह प्रदान करने वाला मंच।',
    heroCta: 'समस्या है? अभी दर्ज करें →',
    heroAudioHint: 'आवाज, वीडियो व फोटो द्वारा आसानी से रिपोर्ट करें',

    // How It Works / User Flow
    howItWorksTitle: 'हमारी कार्य प्रणाली',
    howItWorksSubtitle: 'KisaanSathi के साथ 4 आसान चरणों में पाएं सटीक समाधान',
    step1Num: '1',
    step1Title: 'समस्या दर्ज करें',
    step1Text: 'आवाज (वॉयस), वीडियो स्कैन, फोटो या लिखकर आसानी से फसल की समस्या बताएं।',
    step2Num: '2',
    step2Title: 'AI विश्लेषण',
    step2Text: 'हमारा AI फसल के लक्षणों और कीटों का तुरंत विश्लेषण करता है।',
    step3Num: '3',
    step3Title: 'विशेषज्ञ सलाह',
    step3Text: 'कृषि विस्तार अधिकारी (AEO) सही और सुरक्षित उपचार की पुष्टि करते हैं।',
    step4Num: '4',
    step4Title: 'बेहतर फसल व उपज',
    step4Text: 'सटीक सलाह से फसल सुरक्षित करें और भरपूर पैदावार प्राप्त करें।',

    // AI Feature Deep Dive
    aiFeatureBadge: 'मल्टीमॉडल AI तकनीक',
    aiFeatureTitle: 'AI की शक्ति से कृषि को नई दिशा',
    aiFeatureDesc: 'फसल की बीमारी या कीट पहचानना अब हुआ बेहद आसान। अपनी भाषा में बोलें या पौधे का वीडियो/फोटो लें।',
    aiFeature1: 'आधुनिक AI मॉडल द्वारा अत्यंत सटीक रोग पहचान',
    aiFeature2: 'फोटो, ऑडियो, वीडियो और टेक्स्ट सभी प्रारूपों का पूर्ण समर्थन',
    aiFeature3: 'त्वरित और सरकारी कृषि अधिकारियों द्वारा प्रमाणित सलाह',
    aiFeature4: 'विशेष रूप से भारतीय कृषि और फसलों के लिए निर्मित',

    // Comparison Section
    comparisonTitle: 'पारंपरिक तरीकों की तुलना में हम बेहतर क्यों?',
    comparisonSubtitle: 'धीमे और महंगे तरीकों को छोड़ें, KisaanSathi से पाएं तुरंत समाधान',
    traditionalTitle: 'पारंपरिक तरीका',
    traditionalItem1: 'अधिकारियों या विशेषज्ञों से मिलने में कई दिन लग जाते हैं',
    traditionalItem2: 'सटीक और विश्वसनीय जानकारी मिलना कठिन',
    traditionalItem3: 'यात्रा व परामर्श का अधिक खर्च',
    traditionalItem4: 'देरी से समाधान मिलने पर फसल खराब हो जाती है',
    kisaanTitle: 'KisaanSathi',
    kisaanItem1: 'खेत से कभी भी, कहीं भी 24/7 तत्काल सहायता',
    kisaanItem2: 'AI + प्रमाणित कृषि विस्तार अधिकारी की विशेषज्ञ सलाह',
    kisaanItem3: 'वॉयस या मोबाइल ऐप में अपनी भाषा में आसान उपयोग',
    kisaanItem4: 'मिनटों में तेज व वैज्ञानिक समाधान',

    // Stats Bar
    stat1Value: '10K+',
    stat1Label: 'किसानों का भरोसा',
    stat2Value: '25K+',
    stat2Label: 'सुलझाई गई समस्याएं',
    stat3Value: '50+',
    stat3Label: 'फसलें सम्मिलित',
    stat4Value: '99%',
    stat4Label: 'संतुष्टि रेटिंग',

    // Bottom CTA Banner
    ctaBannerTitle: 'फसल की समस्या के लिए अब इंतजार क्यों?',
    ctaBannerSubtitle: 'KisaanSathi के साथ कदम बढ़ाएं और अपनी फसल को सुरक्षित करें।',
    ctaBannerBtn: 'अभी समस्या दर्ज करें →',

    // Farmer Page / Form
    formTitle: 'फसल की समस्या दर्ज करें',
    formSubtitle: 'कोई लॉगिन या पासवर्ड आवश्यक नहीं है। बोलकर या लिखकर विवरण दें।',
    labelName: 'आपका नाम',
    placeholderName: 'उदा. रमेश सिंह',
    labelPhone: 'मोबाइल नंबर',
    placeholderPhone: 'उदा. 9876543210 या +91 9876543210',
    phoneHint: 'केवल अधिकारियों द्वारा संपर्क हेतु। OTP की आवश्यकता नहीं।',
    labelCrop: 'फसल का नाम (वैकल्पिक)',
    placeholderCustomCrop: 'फसल का नाम लिखें',
    labelDescription: 'समस्या का विवरण (या नीचे बोलें)',
    placeholderDescription: 'लक्षण बताएं: पत्तियां पीली पड़ना, पत्तियों में छेद, तना छेदक कीट, सड़न आदि।',
    labelVoice: 'बोलकर समस्या दर्ज करें (Voice Recording)',
    btnStartRecording: 'बोलकर समस्या बताएं',
    btnStopRecording: 'रिकॉर्डिंग समाप्त',
    btnRecordAgain: 'पुनः बोलें',
    btnClearVoice: 'आवाज हटाएं',
    voiceAttached: 'आवाज रिकॉर्ड हुई',
    voiceRecordingActive: 'रिकॉर्डिंग जारी है... बोलिए',
    voiceHint: 'अपनी भाषा में बोलें। AI आपकी आवाज को टेक्स्ट और लक्षणों में बदल देगा।',
    micPermissionDenied: 'माइक्रोफोन की अनुमति अस्वीकृत। ब्राउज़र सेटिंग्स में माइक्रोफोन की अनुमति दें।',
    micError: 'माइक्रोफोन उपलब्ध नहीं है।',
    voiceUnsupported: 'इस ब्राउज़र में वॉयस रिकॉर्डिंग समर्थित नहीं है।',
    labelPhoto: 'फोटो या वीडियो जोड़ें (वैकल्पिक)',
    btnTakePhoto: 'फोटो लें या गैलरी से चुनें',
    btnRemovePhoto: 'फोटो हटाएं',
    photoHint: 'प्रभावित पत्तियों या कीटों की स्पष्ट फोटो से अधिकारी जल्द निदान कर पाते हैं।',
    labelLocation: 'खेत का स्थान (GPS)',
    gpsDetecting: 'GPS लोकेशन खोजी जा रही है...',
    gpsDetected: 'GPS लोकेशन प्राप्त हुई',
    gpsDenied: 'GPS चालू नहीं है',
    gpsDeniedHint: 'GPS न होने पर भी आपकी रिपोर्ट सफलतापूर्वक दर्ज होगी।',
    btnRetryGps: 'पुनः प्रयास करें',
    btnSubmit: 'समस्या सबमिट करें',
    btnSubmitting: 'सबमिट हो रहा है एवं AI विश्लेषण जारी है...',
    errorTitle: 'त्रुटि हुई',
    valNameRequired: 'कृपया अपना नाम दर्ज करें।',
    valPhoneRequired: 'कृपया 10 अंकों का मोबाइल नंबर दर्ज करें।',
    valDescRequired: 'कृपया समस्या का विवरण दें या आवाज रिकॉर्ड करें।',
    valPhotoSize: 'फोटो का आकार 10MB से कम होना चाहिए।',

    // Confirmation Screen
    successTitle: 'समस्या सफलतापूर्वक दर्ज हो गई',
    successSubtitle: 'आपकी कृषि समस्या हमारे सिस्टम में रिकॉर्ड कर ली गई है',
    refIdLabel: 'संदर्भ संख्या (Reference ID)',
    confirmMessage: 'आपकी फसल समस्या दर्ज कर ली गई है।',
    confirmNextStep: 'आगे के चरणों में यह रिपोर्ट संबंधित कृषि विस्तार अधिकारी को भेजी जाएगी।',
    summaryTitle: 'दर्ज विवरण',
    summaryFarmerName: 'किसान का नाम',
    summaryMobile: 'मोबाइल नंबर',
    summaryCrop: 'फसल',
    summaryGps: 'GPS लोकेशन',
    summaryPhoto: 'फोटो',
    summaryVoice: 'आवाज रिकॉर्डिंग',
    aiInsightsTitle: 'AI आवाज एवं कृषि अर्थ विश्लेषण',
    aiTranscriptLabel: 'बोले गए शब्द (Transcript)',
    aiSummaryLabel: 'कृषि समस्या का सारांश',
    aiSymptomsLabel: 'पहचाने गए लक्षण',
    aiConditionsLabel: 'संभावित बीमारियां / कीट',
    aiAeoReviewLabel: 'कृषि अधिकारी (AEO) प्रत्यक्ष समीक्षा आवश्यक',
    valAttached: 'संलग्न',
    valNone: 'कोई नहीं',
    valNotProvided: 'उपलब्ध नहीं',
    btnReportAnother: 'अन्य समस्या दर्ज करें',
    btnBackHome: 'मुख्य पृष्ठ पर लौटें',

    // Officer Page
    officerTitle: 'कृषि अधिकारी पोर्टल',
    officerSubtitle: 'कृषि विस्तार अधिकारी (AEO) एवं कृषि विभाग',
    officerNoticeTitle: 'अधिकारी लॉगिन',
    officerNoticeText: 'अधिकारी लॉगिन एवं फील्ड प्रबंधन डैशबोर्ड।',
    officerNoticeSubtext: 'किसान बिना लॉगिन किए सीधे फसल समस्याओं की रिपोर्ट कर सकते हैं।',
    btnReturnFarmer: '← किसान रिपोर्टिंग पृष्ठ पर लौटें',

    // Footer
    footerTitle: 'किसानसाथी &mdash; AI आधारित कृषि समस्या निवारण मंच',
    footerSubtext: 'किसानों की समस्याओं को AI एवं कृषि अधिकारियों तक त्वरित पहुंचाने का विश्वसनीय माध्यम।',

    // Crops List
    crops: [
      { value: 'धान', label: 'धान / चावल (Paddy)' },
      { value: 'मिर्च', label: 'मिर्च (Chilli)' },
      { value: 'कपास', label: 'कपास (Cotton)' },
      { value: 'मक्का', label: 'मक्का (Maize)' },
      { value: 'अरहर', label: 'अरहर / तूर (Red Gram)' },
      { value: 'टमाटर', label: 'टमाटर (Tomato)' },
      { value: 'मूंगफली', label: 'मूंगफली (Groundnut)' },
      { value: 'गन्ना', label: 'गन्ना (Sugarcane)' },
      { value: 'अन्य फसल', label: 'अन्य फसल (Other)' },
    ],

    // AI Assistant Conversational Flow
    aiAssistant: {
      screen1Title: 'शिकायत दर्ज करना शुरू करें',
      screen1Subtitle: 'एक साधारण आवाज संदेश में अपने कृषि AI सहायक को अपनी समस्या बताएं। हम विवरण निकालकर स्थानीय कृषि अधिकारी (AEO) तक पहुंचाएंगे।',
      btnStartComplaint: 'शिकायत शुरू करें →',
      greeting: 'अपनी खेती से जुड़ी समस्या के बारे में बताएं।',
      listeningNotice: 'सुन रहे हैं... कृपया अपनी समस्या विस्तार से बोलें',
      processingVoice: 'आपकी आवाज का विश्लेषण किया जा रहा है...',
      btnRecordVoice: '🎙️ समस्या बोलकर बताएं',
      btnStopRecording: '⏹️ बोलना समाप्त हुआ',
      btnRecordAgain: '🔄 पुनः बोलें',
      summaryHeading: 'आपकी शिकायत का विवरण',
      summaryCheckPrompt: 'क्या यह आपकी समस्या का सही विवरण है?',
      btnConfirmSummary: '✓ हाँ, आगे बढ़ें',
      btnEditSummary: '✏️ सुधारें / पुनः बोलें',
      labelCrop: 'फसल',
      labelProblem: 'समस्या',
      labelDuration: 'अवधि',
      labelProgress: 'प्रगति',
      defaultPhotoPrompt: 'पौधे की समस्या को अच्छी तरह समझने के लिए कृपया कुछ फोटो भेजें।',
      btnTakePhoto: '📷 फोटो खींचें',
      btnChooseGallery: '🖼️ गैलरी से चुनें',
      photoCountNotice: '1 से 4 फोटो (कम से कम 1 अच्छी फोटो पर्याप्त है)',
      btnSubmitComplaint: '🚀 कृषि अधिकारी को भेजें',
      submittingText: 'शिकायत दर्ज की जा रही है...',
      photoRetryTitle: 'स्पष्ट फोटो आवश्यक',
      photoRetryPrompt: 'समस्या को समझने के लिए फोटो स्पष्ट नहीं है। कृपया प्रभावित पौधे या हिस्से को स्पष्ट रूप से दिखाते हुए दूसरी फोटो भेजें।',
      photoWrongCropPrompt: 'अपलोड की गई फोटो आपकी फसल समस्या से संबंधित नहीं लग रही है। आपकी आवाज की शिकायत सुरक्षित है। कृपया प्रभावित पौधे की स्पष्ट फोटो भेजें।',
      photoHealthyCropPrompt: 'अपलोड की गई फोटो में कोई कीट या रोग का लक्षण नहीं दिख रहा है। कृपया प्रभावित हिस्से की स्पष्ट फोटो भेजें।',
      btnRetryPhoto: '📷 दूसरी फोटो भेजें',
      voicePreservedNote: '✓ आपकी आवाज सुरक्षित है, दोबारा बोलने की आवश्यकता नहीं है।',
      similarIssuesTitle: 'समान समस्याओं की जांच',
      similarIssuesIntro: 'आपकी शिकायत आपके स्थानीय कृषि अधिकारी (AEO) तक पहुंचाई जा रही है। जांचें कि क्या इनमें से कोई पिछला मामला आपकी फसल समस्या से मेल खाता है:',
      btnLooksLikeMyProblem: 'मेरी समस्या जैसा दिखता है',
      btnConfirmIssue: '✓ समस्या की पुष्टि करें',
      btnNoneOfTheseMatch: 'इनमें से कोई मेल नहीं खाता →',
      noSimilarIssuesFound: 'आस-पास कोई समान पिछला मामला नहीं मिला। आपकी शिकायत सीधे कृषि अधिकारी को भेजी गई है।',
      similarIssuesCheckFailed: 'आपकी शिकायत सुरक्षित रूप से दर्ज कर ली गई है। पुष्टि की ओर बढ़ रहे हैं...',
      aeoVerifiedBadge: 'कृषि अधिकारी द्वारा सत्यापित',
      previousOutcomeLabel: 'पिछले मामले का परिणाम',
      btnContinuing: 'जारी है...',
      successHeading: 'शिकायत सफलतापूर्वक दर्ज हो गई!',
      successSubheading: 'आपके स्थानीय कृषि विस्तार अधिकारी (AEO) को सूचित कर दिया गया है।',
      trackingRefLabel: 'ट्रैकिंग संदर्भ संख्या',
      btnReportAnother: 'अन्य समस्या दर्ज करें',
      btnViewMyIssues: '📋 मेरी समस्याएं',
    },
  },

  ta: {
    // Brand & Nav
    appName: 'KisaanSathi',
    tagline: 'உழவர் தளம்',
    navHome: 'முகப்பு',
    navServices: 'சேவைகள்',
    navAbout: 'பற்றி',
    navContact: 'தொடர்பு',
    navReport: 'சிக்கலைப் புகாரளிக்கவும்',
    navMyFarm: 'என் பண்ணை',
    navOfficerLogin: 'அதிகாரி உள்நுழைவு',
    apiConnected: 'சர்வர் இணைக்கப்பட்டது',
    apiConnecting: 'இணைக்கிறது...',
    apiOffline: 'சர்வர் ஆஃப்லைன்',

    // Landing Page Hero
    heroBadge: 'நேரடி உழவர் உதவி',
    heroBrand: 'KisaanSathi',
    heroTitle: 'உங்கள் பயிருக்கான ஸ்மார்ட் துணை',
    heroDescription: 'குரல், வீடியோ மற்றும் புகைப்படங்கள் மூலம் பயிர் நோய்களை AI ஆய்வு செய்து விவசாய அதிகாரிகளிடமிருந்து விரைவான தீர்வுகளை வழங்குகிறது.',
    heroCta: 'சந்தேகம் உள்ளதா? புகாரளிக்கவும் →',
    heroAudioHint: 'குரல், வீடியோ மற்றும் புகைப்படம் மூலம் பதிவு செய்யலாம்',

    // How It Works / User Flow
    howItWorksTitle: 'இது எப்படி வேலை செய்கிறது?',
    howItWorksSubtitle: '4 எளிய படிகளில் உங்கள் பயிர் சிக்கலுக்கு உடனடி தீர்வு',
    step1Num: '1',
    step1Title: 'சிக்கலைப் பதிவு செய்யவும்',
    step1Text: 'குரல், வீடியோ ஸ்கேன், புகைப்படம் அல்லது எழுதி உங்கள் தாய்மொழியில் தெரிவிக்கவும்.',
    step2Num: '2',
    step2Title: 'AI ஆய்வு',
    step2Text: 'எங்கள் AI பயிர் அறிகுறிகளை உடனடியாக பகுப்பாய்வு செய்கிறது.',
    step3Num: '3',
    step3Title: 'நிபுணர் ஆலோசனை',
    step3Text: 'வேளாண் விரிவாக்க அலுவலர்கள் (AEO) சரியான மருந்துகளை பரிந்துரைக்கின்றனர்.',
    step4Num: '4',
    step4Title: 'சிறந்த விளைச்சல்',
    step4Text: 'துல்லியமான தீர்வு மூலம் பயிர்களைப் பாதுகாத்து அதிக மகசூல் பெறுங்கள்.',

    // AI Feature Deep Dive
    aiFeatureBadge: 'AI தொழில்நுட்பம்',
    aiFeatureTitle: 'AI மூலம் விவசாயத்திற்கு புதிய வழி',
    aiFeatureDesc: 'பயிர் நோய்களைக் கண்டறிவது இப்போது மிகவும் எளிது. தமிழில் பேசலாம் அல்லது வீடியோ எடுக்கலாம்.',
    aiFeature1: 'மேம்பட்ட AI மாதிரிகள் மூலம் மிகத் துல்லியமான பகுப்பாய்வு',
    aiFeature2: 'புகைப்படங்கள், ஆடியோ, வீடியோ மற்றும் உரை ஆதரவு',
    aiFeature3: 'அரசு வேளாண் அதிகாரிகளால் சரிபார்க்கப்பட்ட நம்பகமான பரிந்துரைகள்',
    aiFeature4: 'இந்திய வேளாண்மைக்கு பிரத்யேகமாக உருவாக்கப்பட்டது',

    // Comparison Section
    comparisonTitle: 'பாரம்பரிய முறைகளை விட நாம் ஏன் சிறந்தது?',
    comparisonSubtitle: 'பழைய மெதுவான முறைகளுக்கு பதிலாக KisaanSathi மூலம் விரைவான பலன்கள்',
    traditionalTitle: 'பாரம்பரிய முறை',
    traditionalItem1: 'அதிகாரிகளை நேரில் சந்திக்க பல நாட்கள் ஆகலாம்',
    traditionalItem2: 'துல்லியமான தகவல்கள் கிடைப்பது கடினம்',
    traditionalItem3: 'பயணச் செலவுகள் அதிகம்',
    traditionalItem4: 'தாமதமான ஆலோசனை பயிர் சேதத்தை அதிகரிக்கிறது',
    kisaanTitle: 'KisaanSathi',
    kisaanItem1: 'வயலில் இருந்தே 24/7 உடனடி உதவி',
    kisaanItem2: 'AI மற்றும் வேளாண் அதிகாரிகளின் நிபுணர் வழிகாட்டுதல்',
    kisaanItem3: 'உங்கள் தாய்மொழியில் மிக எளிய பயன்பாடு',
    kisaanItem4: 'சில நிமிடங்களில் விரைவான மற்றும் அறிவியல் பூர்வமான தீர்வு',

    // Stats Bar
    stat1Value: '10K+',
    stat1Label: 'விவசாயிகளின் நம்பிக்கை',
    stat2Value: '25K+',
    stat2Label: 'தீர்க்கப்பட்ட சிக்கல்கள்',
    stat3Value: '50+',
    stat3Label: 'பயிர்கள் சேர்க்கப்பட்டுள்ளன',
    stat4Value: '99%',
    stat4Label: 'திருப்தி மதிப்பீடு',

    // Bottom CTA Banner
    ctaBannerTitle: 'பயிர் சிக்கலுக்கு இனி காத்திருக்க வேண்டாம்!',
    ctaBannerSubtitle: 'KisaanSathi உடன் இணைந்து பயிரை பாதுகாத்துக் கொள்ளுங்கள்.',
    ctaBannerBtn: 'இப்போதே பதிவு செய்யவும் →',

    // Farmer Page / Form
    formTitle: 'பயிர் பிரச்சனையைப் புகாரளிக்கவும்',
    formSubtitle: 'உள்நுழைவு தேவையில்லை. பேசியோ அல்லது எழுதியோ தெரிவிக்கவும்.',
    labelName: 'உங்கள் பெயர்',
    placeholderName: 'எ.கா. குமார்',
    labelPhone: 'கைபேசி எண்',
    placeholderPhone: 'எ.கா. 9876543210 அல்லது +91 9876543210',
    phoneHint: 'அதிகாரிகள் தொடர்பு கொள்ள மட்டுமே. OTP தேவையில்லை.',
    labelCrop: 'பயிர் பெயர் (விருப்பமானது)',
    placeholderCustomCrop: 'பயிர் பெயரை உள்ளிடவும்',
    labelDescription: 'பிரச்சனை விவரம் (அல்லது கீழே பேசவும்)',
    placeholderDescription: 'இலைகள் மஞ்சள் நிறமாதல், இலைகளில் துளைகள், பூச்சித் தாக்குதல் போன்றவற்றை விவரிக்கவும்.',
    labelVoice: 'குரல் மூலம் புகாரளிக்கவும் (Voice Recording)',
    btnStartRecording: 'பேசிப் புகாரளிக்கவும்',
    btnStopRecording: 'பதிவு முடிந்தது',
    btnRecordAgain: 'மீண்டும் பேசவும்',
    btnClearVoice: 'குரலை நீக்கு',
    voiceAttached: 'குரல் பதிவு செய்யப்பட்டது',
    voiceRecordingActive: 'பதிவாகிறது... பேசவும்',
    voiceHint: 'தமிழில் தெளிவாகப் பேசவும். AI உங்கள் பேச்சை ஆய்வு செய்யும்.',
    micPermissionDenied: 'மைக் அனுமதி மறுக்கப்பட்டது. பிரவுசர் அமைப்புகளில் மைக்கை அனுமதிக்கவும்.',
    micError: 'மைக்கை அணுக முடியவில்லை.',
    voiceUnsupported: 'இந்த உலாவியில் குரல் பதிவு வசதி இல்லை.',
    labelPhoto: 'புகைப்படம் அல்லது வீடியோ (விருப்பமானது)',
    btnTakePhoto: 'புகைப்படம் எடுக்கவும் / கேலரி',
    btnRemovePhoto: 'புகைப்படத்தை நீக்கு',
    photoHint: 'தெளிவான புகைப்படங்கள் அதிகாரிகள் விரைவாக நோய் கண்டறிய உதவும்.',
    labelLocation: 'வயல் இருப்பிடம் (GPS)',
    gpsDetecting: 'GPS இருப்பிடத்தைக் கண்டறிகிறது...',
    gpsDetected: 'GPS இருப்பிடம் கண்டறியப்பட்டது',
    gpsDenied: 'GPS இயக்கப்படவில்லை',
    gpsDeniedHint: 'GPS இல்லாமலும் உங்கள் புகார் வெற்றிகரமாக சமர்ப்பிக்கப்படும்.',
    btnRetryGps: 'மீண்டும் முயற்சிக்கவும்',
    btnSubmit: 'சிக்கலைச் சமர்ப்பிக்கவும்',
    btnSubmitting: 'சமர்ப்பிக்கிறது & குரலை ஆய்வு செய்கிறது...',
    errorTitle: 'பிழை ஏற்பட்டது',
    valNameRequired: 'தயவுசெய்து உங்கள் பெயரை உள்ளிடவும்.',
    valPhoneRequired: 'தயவுசெய்து 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.',
    valDescRequired: 'தயவுசெய்து பிரச்சனையை விவரிக்கவும் அல்லது பேசிப் பதிவு செய்யவும்.',
    valPhotoSize: 'புகைப்படத்தின் அளவு 10MB க்கும் குறைவாக இருக்க வேண்டும்.',

    // Confirmation Screen
    successTitle: 'சிக்கல் வெற்றிகரமாக பதிவு செய்யப்பட்டது',
    successSubtitle: 'உங்கள் விவசாயப் பிரச்சனை பதிவு செய்யப்பட்டுள்ளது',
    refIdLabel: 'குறிப்பு எண் (Reference ID)',
    confirmMessage: 'உங்கள் பயிர் பிரச்சனை எங்கள் அமைப்பில் பதிவு செய்யப்பட்டுள்ளது.',
    confirmNextStep: 'அடுத்த கட்டத்தில் இது தொடர்புடைய வேளாண் விரிவாக்க அலுவலருக்கு அனுப்பப்படும்.',
    summaryTitle: 'சமர்ப்பிக்கப்பட்ட விவரங்கள்',
    summaryFarmerName: 'விவசாயி பெயர்',
    summaryMobile: 'கைபேசி எண்',
    summaryCrop: 'பயிர்',
    summaryGps: 'GPS இருப்பிடம்',
    summaryPhoto: 'புகைப்படம்',
    summaryVoice: 'குரல் பதிவு',
    aiInsightsTitle: 'AI குரல் & வேளாண் ஆய்வுத் தகவல்',
    aiTranscriptLabel: 'பேசிய உரை (Transcript)',
    aiSummaryLabel: 'வேளாண் சுருக்கம்',
    aiSymptomsLabel: 'கண்டறியப்பட்ட அறிகுறிகள்',
    aiConditionsLabel: 'சாத்தியமான பாதிப்புகள்',
    aiAeoReviewLabel: 'வேளாண் அதிகாரி நேரடி ஆய்வு தேவை',
    valAttached: 'இணைக்கப்பட்டுள்ளது',
    valNone: 'இல்லை',
    valNotProvided: 'வழங்கப்படவில்லை',
    btnReportAnother: 'மற்றொரு சிக்கலைப் புகாரளிக்கவும்',
    btnBackHome: 'முகப்புக்குத் திரும்பு',

    // Officer Page
    officerTitle: 'வேளாண் அலுவலர் தளம்',
    officerSubtitle: 'வேளாண் விரிவாக்க அலுவலர்கள் (AEO) தளம்',
    officerNoticeTitle: 'அலுவலர் உள்நுழைவு',
    officerNoticeText: 'அலுவலர் உள்நுழைவு மற்றும் களப்பணி மேலாண்மை.',
    officerNoticeSubtext: 'விவசாயிகள் உள்நுழையாமல் நேரடியாகப் பயிர் பிரச்சனைகளைப் புகாரளிக்கலாம்.',
    btnReturnFarmer: '← உழவர் புகார் பக்கத்திற்குத் திரும்பவும்',

    // Footer
    footerTitle: 'KisaanSathi &mdash; AI வேளாண் ஆலோசனை மற்றும் தீர்வு தளம்',
    footerSubtext: 'விவசாயிகளின் புகார்களை நேரடியாக வேளாண் அதிகாரிகளுக்கு கொண்டு சேர்க்கிறது.',

    // Crops List
    crops: [
      { value: 'நெல்', label: 'நெல் (Paddy)' },
      { value: 'மிளகாய்', label: 'மிளகாய் (Chilli)' },
      { value: 'பருத்தி', label: 'பருத்தி (Cotton)' },
      { value: 'மக்காச்சோளம்', label: 'மக்காச்சோளம் (Maize)' },
      { value: 'துவரை', label: 'துவரை (Red Gram)' },
      { value: 'தக்காளி', label: 'தக்காளி (Tomato)' },
      { value: 'நிலக்கடலை', label: 'நிலக்கடலை (Groundnut)' },
      { value: 'கரும்பு', label: 'கரும்பு (Sugarcane)' },
      { value: 'மற்ற பயிர்', label: 'மற்ற பயிர் (Other)' },
    ],

    // AI Assistant Conversational Flow
    aiAssistant: {
      screen1Title: 'புகார் பதிவு செய்ய தொடங்குங்கள்',
      screen1Subtitle: 'உங்கள் விவசாய பிரச்சனையை ஒரே குரல் பதிவில் எளிதாக கூறுங்கள். உங்கள் பகுதி வேளாண்மை அலுவலருக்கு (AEO) அனுப்பப்படும்.',
      btnStartComplaint: 'தொடங்குங்கள் →',
      greeting: 'உங்கள் விவசாய பிரச்சனையைப் பற்றி சொல்லுங்கள்.',
      listeningNotice: 'கேட்கிறது... உங்கள் பிரச்சனையை தெளிவாக பேசுங்கள்',
      processingVoice: 'உங்கள் குரல் ஆய்வு செய்யப்படுகிறது...',
      btnRecordVoice: '🎙️ பிரச்சனையை பேசுங்கள்',
      btnStopRecording: '⏹️ பேசி முடித்தேன்',
      btnRecordAgain: '🔄 மீண்டும் பேசுங்கள்',
      summaryHeading: 'உங்கள் புகார் விவரம்',
      summaryCheckPrompt: 'இது உங்கள் பிரச்சனையை சரியாக விவரிக்கிறதா?',
      btnConfirmSummary: '✓ ஆம், தொடரவும்',
      btnEditSummary: '✏️ திருத்தவும் / மீண்டும் பேசவும்',
      labelCrop: 'பயிர்',
      labelProblem: 'பிரச்சனை',
      labelDuration: 'கால அளவு',
      labelProgress: 'நிலை',
      defaultPhotoPrompt: 'செடியின் பிரச்சனையை சரியாக புரிந்து கொள்ள சில புகைப்படங்களை அனுப்பவும்.',
      btnTakePhoto: '📷 புகைப்படம் எடுக்கவும்',
      btnChooseGallery: '🖼️ கேலரியிலிருந்து தேர்வு செய்க',
      photoCountNotice: '1 முதல் 4 படங்கள் (1 நல்ல படம் போதுமானது)',
      btnSubmitComplaint: '🚀 வேளாண் அலுவலருக்கு அனுப்புக',
      submittingText: 'பதிவு செய்யப்படுகிறது...',
      photoRetryTitle: 'தெளிவான புகைப்படம் தேவை',
      photoRetryPrompt: 'பிரச்சனையை அடையாளம் காண புகைப்படம் தெளிவாக இல்லை. தயவுசெய்து பாதிக்கப்பட்ட பகுதியை தெளிவாக காட்டும் மற்றொரு புகைப்படத்தை அனுப்பவும்.',
      photoWrongCropPrompt: 'பதிவேற்றப்பட்ட புகைப்படம் உங்கள் பயிர் பிரச்சனையுடன் தொடர்புடையதாக தெரியவில்லை. உங்கள் குரல் பதிவு பாதுகாப்பாக உள்ளது. தயவுசெய்து பாதிக்கப்பட்ட பயிரின் தெளிவான புகைப்படத்தை அனுப்பவும்.',
      photoHealthyCropPrompt: 'பதிவேற்றிய புகைப்படத்தில் எந்த சேதமும் தெரியவில்லை. தயவுசெய்து பாதிக்கப்பட்ட பகுதியை தெளிவாக காட்டும் புகைப்படத்தை அனுப்பவும்.',
      btnRetryPhoto: '📷 வேறு புகைப்படம் அனுப்பவும்',
      voicePreservedNote: '✓ உங்கள் குரல் பதிவு பாதுகாப்பாக உள்ளது.',
      similarIssuesTitle: 'ஒத்த பிரச்சினைகள் சரிபார்ப்பு',
      similarIssuesIntro: 'உங்கள் புகார் உள்ளூர் வேளாண்மை அலுவலருக்கு (AEO) அனுப்பப்படுகிறது. முந்தைய இந்த வழக்குகள் உங்கள் பயிர் பிரச்சனையுடன் பொருந்துகிறதா என்பதைப் பாருங்கள்:',
      btnLooksLikeMyProblem: 'என் பிரச்சினை போன்றது',
      btnConfirmIssue: '✓ பிரச்சினையை உறுதிப்படுத்துங்கள்',
      btnNoneOfTheseMatch: 'இவற்றில் எதுவும் பொருந்தவில்லை →',
      noSimilarIssuesFound: 'அருகில் ஒத்த முந்தைய வழக்குகள் எதுவும் காணப்படவில்லை. உங்கள் புகார் நேரடியாக உங்கள் ஏஇஓ-வுக்கு அனுப்பப்பட்டது.',
      similarIssuesCheckFailed: 'உங்கள் புகார் பாதுகாப்பாக பதிவு செய்யப்பட்டுள்ளது...',
      aeoVerifiedBadge: 'வேளாண்மை அலுவலரால் சரிபார்க்கப்பட்டது',
      previousOutcomeLabel: 'முந்தைய வழக்கின் முடிவு',
      btnContinuing: 'தொடர்கிறது...',
      successHeading: 'புகார் வெற்றிகரமாக பதிவானது!',
      successSubheading: 'உங்கள் வேளாண் அலுவலருக்கு (AEO) தகவல் தெரிவிக்கப்பட்டது.',
      trackingRefLabel: 'குறிப்பு எண் (Reference ID)',
      btnReportAnother: 'மற்றொரு பிரச்சனையை பதிவு செய்',
      btnViewMyIssues: '📋 என் புகார்கள்',
    },
  },

  kn: {
    // Brand & Nav
    appName: 'ಕಿಸಾನ್‌ಸಾಥಿ',
    tagline: 'ಸ್ಮಾರ್ಟ್ ಬೆಳೆ ಸಂಗಾತಿ',
    navHome: 'ಮುಖಪುಟ',
    navServices: 'ಸೇವೆಗಳು',
    navAbout: 'ನಮ್ಮ ಬಗ್ಗೆ',
    navContact: 'ಸಂಪರ್ಕಿಸಿ',
    navReport: 'ಸಮಸ್ಯೆ ದಾಖಲಿಸಿ',
    navMyFarm: 'ನನ್ನ ಜಮೀನು',
    navOfficerLogin: 'ಅಧಿಕಾರಿ ಲಾಗಿನ್',
    apiConnected: 'ಸರ್ವರ್ ಸಂಪರ್ಕಗೊಂಡಿದೆ',
    apiConnecting: 'ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...',
    apiOffline: 'ಸರ್ವರ್ ಆಫ್‌ಲೈನ್',

    crops: [
      { value: 'ಭತ್ತ', label: 'ಭತ್ತ (Paddy)' },
      { value: 'ಮೆಣಸಿನಕಾಯಿ', label: 'ಮೆಣಸಿನಕಾಯಿ (Chilli)' },
      { value: 'ಹತ್ತಿ', label: 'ಹತ್ತಿ (Cotton)' },
      { value: 'ಮೆಕ್ಕೆಜೋಳ', label: 'ಮೆಕ್ಕೆಜೋಳ (Maize)' },
      { value: 'ತೊಗರಿ', label: 'ತೊಗರಿ (Red Gram)' },
      { value: 'ಟೊಮೆಟೊ', label: 'ಟೊಮೆಟೊ (Tomato)' },
      { value: 'ಕಡಲೆಕಾಯಿ', label: 'ಕಡಲೆಕಾಯಿ (Groundnut)' },
      { value: 'ಕಬ್ಬು', label: 'ಕಬ್ಬು (Sugarcane)' },
      { value: 'ಇತರ ಬೆಳೆ', label: 'ಇತರ ಬೆಳೆ (Other)' },
    ],

    // AI Assistant Conversational Flow
    aiAssistant: {
      screen1Title: 'ದೂರು ದಾಖಲಿಸಲು ಪ್ರಾರಂಭಿಸಿ',
      screen1Subtitle: 'ನಿಮ್ಮ ಕೃಷಿ ಸಮಸ್ಯೆಯನ್ನು ಒಂದೇ ಧ್ವನಿ ಸಂದೇಶದಲ್ಲಿ ಹೇಳಿ. ನಾವು ಸ್ಥಳೀಯ ಕೃಷಿ ವಿಸ್ತರಣಾ ಅಧಿಕಾರಿಗೆ (AEO) ಕಳುಹಿಸುತ್ತೇವೆ.',
      btnStartComplaint: 'ಪ್ರಾರಂಭಿಸಿ →',
      greeting: 'ನಿಮ್ಮ ಕೃಷಿ ಸಮಸ್ಯೆಯ ಬಗ್ಗೆ ತಿಳಿಸಿ.',
      listeningNotice: 'ಕೇಳಿಸಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ... ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಮಾತನಾಡಿ',
      processingVoice: 'ನಿಮ್ಮ ಧ್ವನಿಯನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
      btnRecordVoice: '🎙️ ಸಮಸ್ಯೆಯನ್ನು ಮಾತನಾಡಿ',
      btnStopRecording: '⏹️ ಮುಗಿಯಿತು',
      btnRecordAgain: '🔄 ಮತ್ತೆ ಮಾತನಾಡಿ',
      summaryHeading: 'ನಿಮ್ಮ ದೂರಿನ ವಿವರಗಳು',
      summaryCheckPrompt: 'ಇದು ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಸರಿಯಾಗಿ ವಿವರಿಸುತ್ತದೆಯೇ?',
      btnConfirmSummary: '✓ ಹೌದು, ಮುಂದುವರಿಯಿರಿ',
      btnEditSummary: '✏️ ಸರಿಪಡಿಸಿ / ಮತ್ತೆ ಮಾತನಾಡಿ',
      labelCrop: 'ಬೆಳೆ',
      labelProblem: 'ಸಮಸ್ಯೆ',
      labelDuration: 'ಅವಧಿ',
      labelProgress: 'ಪ್ರಗತಿ',
      defaultPhotoPrompt: 'ಸಸ್ಯದ ಸಮಸ್ಯೆಯನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ದಯವಿಟ್ಟು ಕೆಲವು ಫೋಟೋಗಳನ್ನು ಕಳುಹಿಸಿ.',
      btnTakePhoto: '📷 ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ',
      btnChooseGallery: '🖼️ ಗ್ಯಾಲರಿಯಿಂದ ಆರಿಸಿ',
      photoCountNotice: '1 ರಿಂದ 4 ಫೋಟೋಗಳು (1 ಉತ್ತಮ ಫೋಟೋ ಸಾಕು)',
      btnSubmitComplaint: '🚀 ಕೃಷಿ ಅಧಿಕಾರಿಗೆ ಕಳುಹಿಸಿ',
      submittingText: 'ದೂರು ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
      photoRetryTitle: 'ಸ್ಪಷ್ಟ ಫೋಟೋ ಅಗತ್ಯವಿದೆ',
      photoRetryPrompt: 'ಸಮಸ್ಯೆಯನ್ನು ಗುರುತಿಸಲು ಫೋಟೋ ಸ್ಪಷ್ಟವಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಬಾಧಿತ ಸಸ್ಯದ ಸ್ಪಷ್ಟ ಫೋಟೋ ಕಳುಹಿಸಿ.',
      photoWrongCropPrompt: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಫೋಟೋ ನಿಮ್ಮ ಬೆಳೆ ಸಮಸ್ಯೆಗೆ ಸಂಬಂಧಿಸಿದಂತೆ ಕಾಣಿಸುತ್ತಿಲ್ಲ. ನಿಮ್ಮ ಧ್ವನಿ ದೂರು ಸುರಕ್ಷಿತವಾಗಿದೆ. ದಯವಿಟ್ಟು ಬಾಧಿತ ಬೆಳೆಯ ಸ್ಪಷ್ಟ ಫೋಟೋ ಕಳುಹಿಸಿ.',
      photoHealthyCropPrompt: 'ಅಪ್‌ಲೋಡ್ ಮಾಡಿದ ಫೋಟೋದಲ್ಲಿ ಯಾವುದೇ ರೋಗ ಅಥವಾ ಹಾನಿಯ ಲಕ್ಷಣಗಳು ಕಂಡುಬರುತ್ತಿಲ್ಲ. ದಯವಿಟ್ಟು ಬಾಧಿತ ಭಾಗದ ಸ್ಪಷ್ಟ ಫೋಟೋ ಕಳುಹಿಸಿ.',
      btnRetryPhoto: '📷 ಇನ್ನೊಂದು ಫೋಟೋ ಕಳುಹಿಸಿ',
      voicePreservedNote: '✓ ನಿಮ್ಮ ಧ್ವನಿ ದಾಖಲೆ ಸುರಕ್ಷಿತವಾಗಿದೆ.',
      similarIssuesTitle: 'ಸಮಾನ ಸಮಸ್ಯೆಗಳ ಪರಿಶೀಲನೆ',
      similarIssuesIntro: 'ನಿಮ್ಮ ದೂರನ್ನು ಸ್ಥಳೀಯ ಕೃಷಿ ಅಧಿಕಾರಿಗೆ (AEO) ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ. ಈ ಹಿಂದಿನ ಪ್ರಕರಣಗಳು ನಿಮ್ಮ ಬೆಳೆ ಸಮಸ್ಯೆಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತವೆಯೇ ಪರಿಶೀಲಿಸಿ:',
      btnLooksLikeMyProblem: 'ನನ್ನ ಸಮಸ್ಯೆಯಂತೆಯೇ ಇದೆ',
      btnConfirmIssue: '✓ ಸಮಸ್ಯೆಯನ್ನು ದೃಢೀಕರಿಸಿ',
      btnNoneOfTheseMatch: 'ಇವುಗಳಲ್ಲಿ ಯಾವುದೂ ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ →',
      noSimilarIssuesFound: 'ಹತ್ತಿರದಲ್ಲಿ ಯಾವುದೇ ಸಮಾನ ಪ್ರಕರಣಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ನಿಮ್ಮ ದೂರನ್ನು ನೇರವಾಗಿ ಕೃಷಿ ಅಧಿಕಾರಿಗೆ ಸಲ್ಲಿಸಲಾಗಿದೆ.',
      similarIssuesCheckFailed: 'ನಿಮ್ಮ ದೂರನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ...',
      aeoVerifiedBadge: 'ಕೃಷಿ ಅಧಿಕಾರಿಯಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      previousOutcomeLabel: 'ಹಿಂದಿನ ಪ್ರಕರಣದ ಫಲಿತಾಂಶ',
      btnContinuing: 'ಮುಂದುವರಿಯುತ್ತಿದೆ...',
      successHeading: 'ದೂರು ಯಶಸ್ವಿಯಾಗಿ ದಾಖಲಾಗಿದೆ!',
      successSubheading: 'ನಿಮ್ಮ ಕೃಷಿ ಅಧಿಕಾರಿಗೆ (AEO) ಮಾಹಿತಿ ತಲುಪಿದೆ.',
      trackingRefLabel: 'ಟ್ರ್ಯಾಕಿಂಗ್ ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ',
      btnReportAnother: 'ಮತ್ತೊಂದು ಸಮಸ್ಯೆ ದಾಖಲಿಸಿ',
      btnViewMyIssues: '📋 ನನ್ನ ದೂರುಗಳು',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('kisaansathi_lang') || 'te';
  });

  const changeLanguage = (langCode) => {
    if (translations[langCode]) {
      setCurrentLang(langCode);
      localStorage.setItem('kisaansathi_lang', langCode);
    }
  };

  const langNames = {
    te: 'తెలుగు',
    en: 'English',
    hi: 'हिन्दी',
    ta: 'தமிழ்',
    kn: 'ಕನ್ನಡ',
    mr: 'मराठी',
  };

  const t = translations[currentLang] || translations.hi || translations.te;


  const currentLanguageName = langNames[currentLang] || 'తెలుగు';

  return (
    <LanguageContext.Provider
      value={{
        currentLang,
        changeLanguage,
        t,
        languages: LANGUAGES,
        currentLanguageName,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

