-- ==============================================================================
-- RythuBandhu - Phase 2 Demo Seed Data (Optional)
-- Clean, realistic demonstration records to verify relations and geospatial queries
-- ==============================================================================
